### ISSUE TITLE
Implementing Around Screen (3) - develop point maps 

### ISSUE THREAD

**Issue by flowersayo** [EFUB-ZEJE/ZEJE-FrontEnd#10]
#  둘러보기 - 포인트 지도 개발

- [x] 구글 맵 띄우기
- [ ] 오늘의 포인트 스팟 목록
- [ ] 지도에 현재 내위치 표시하기 -> 구글 지도 api 호출 
- [ ] 꽃봉오리 스팟 리스트 맵핑하기 
- [ ] 꽃봉오리 클릭시 스팟 상세 정보 보이기
   - 스와이프 뷰 구현 -> 그냥 바텀 모달로 처리 
- [ ] 꽃봉오리 획득 기능 구현
   - 내위치와 해당 꽃봉오리 스팟 간의 거리차 구하기 -> harversine npm 패키지 이용하면 될듯 
   - 100m이내인지 아닌지 판별해서 승낙 or 거절 

## 첫화면 / 안내화면

![image](https://user-images.githubusercontent.com/86418674/181709277-17fe56ed-236f-4011-af6c-d76f8693eca8.png)

![image](https://user-images.githubusercontent.com/86418674/182373071-e80c3f44-2875-4b72-b0bc-df9605e19d0e.png)

- [x] getPossibleFlowersModal.js

- [x] getAllFlowersModal.js

- [x] NotFoundModal.js

- [ ] NotFoundModal_extra.js

- [ ] DistanceToSpotModal.js

- [ ] ArriveSpotModal.js

---

## 마커클릭 

![image](https://user-images.githubusercontent.com/86418674/181709783-d807ba24-03d5-4499-8a6b-827c79518e5d.png)

## 친환경 스팟 도착 
![image](https://user-images.githubusercontent.com/86418674/181709931-70a8b288-9092-4536-a046-46df8682ed37.png)

## 리스트뷰 

![image](https://user-images.githubusercontent.com/86418674/181709961-ab256433-b8d5-4f56-8c54-42bfafef0d87.png)

- [x] 리스트뷰

![image](https://user-images.githubusercontent.com/86418674/181801075-6c399ddf-309e-4e54-8b50-3cbc5972f041.png)

**Comment by flowersayo** [comment]
[React Native] RN - 환경 변수를 활용한 API key 숨기기
: 개발환경에서 API 키가 노출되면 안된다고 하여 아래 블로그 링크 주소 참고하여 .env 파일 세팅하였습니다 :) 

https://ssilook.tistory.com/179

**Comment by flowersayo** [comment]
# React-Native 를 통한 카카오맵 띄우기
: 제가 며칠간 열심히 서치를 해봤는데 React-Native에서 카카오맵을 띄우도록 성공한 것이 웹뷰로 카카오맵을 띄우는 사례밖에 없어서 커뮤니티 채널에 네이티브로 띄우는 방법이 없는지 여쭤보니 SDK를 기반으로 브릿지 코드를 생성해서 가능하다고 하시는데 고급영역이어서 시간이 오래걸릴 수 있을 것이라고 하네용.. (카카오맵 API가 총 안드로이드(자바), IOS(스위프트), 웹(React) 전용으로 세개 만들어져 있는데 아무래도 React-Native에서 쓸 수 있게끔 연결하는 과정을 브릿지라고 하시는 것 같은데 짧은 시간내에 가능할지 모르겠어요 😢) 

아무래도 카카오API 를 활용하면 유리한 공모전이기도 하고,  본래는 시간이 오래걸리더라도 가이드라인만 명확하면 천천히 따라해볼 의향이 있었는데 여태껏 찾은 자료들도 아래와 같이 설명이 불분명하고(제가 아직 경험이 부족해서 이해를 잘 못하는 것일수도 있어용.. 웹서버도 따로 세팅을 해야하는 것 같던데 ㅠㅠ 혹시 어플리케이션 웹뷰로 구현해보신 분 계신가요? ) React-Native 와 호환이 잘되는 건 구글맵인 것 같은데 혹시 어떻게 생각하시나요?!

**React-Native 에서 kakao map 웹뷰로 띄우기** 

https://webruden.tistory.com/302

@JangAyeon @dazzlynnnn @SJ-Lee33 

![image](https://user-images.githubusercontent.com/86418674/181673660-8268d7db-c9c7-493e-99e0-1dec0b851281.png)

**Comment by SJ-Lee33** [comment]
> # React-Native 를 통한 카카오맵 띄우기
> : 제가 며칠간 React-Native 에서 카카오맵을 띄우는 방법을 열심히 서치를 해봤는데 **React-Native에서 카카오맵을 띄우도록 성공한 것이 웹뷰로 카카오맵을 띄우는 사례밖에 없어서** ( or 구현된 브릿지 라이브러리인 https://github.com/jiggag/react-native-kakao-maps 를 이용하는 방법도 있으나 단순히 마커 찍는 기능만 이용가능) react-native 커뮤니티 채널에 네이티브로 띄우는 방법밖에 없는지도 여쭤보니 네이티브 SDK [https://apis.map.kakao.com/를](https://apis.map.kakao.com/%EB%A5%BC) 기반으로 브릿지 코드를 생성해서 가능하다고 하시는데 고급영역이어서 초보 분들께는 어려울 수 있을 것이라고 하십니다 (카카오맵 API가 총 안드로이드(자바,코틀린), IOS(스위프트), 웹(React) 전용으로 세개 만들어져 있는데 아무래도 React-Native에서 쓸 수 있게끔 연결하는 코드를 제작하는 과정을 브릿지라고 하시는 것 같아요)
> 
> ![image](https://user-images.githubusercontent.com/86418674/181673660-8268d7db-c9c7-493e-99e0-1dec0b851281.png)
> 
> 그러나 브릿지 코드 부문은 제가 아직 한번도 도전해보지 않은 영역이라 현재 수준에서는 구현이 어려울거라는 생각이 들었습니다. 죄송합니다 😢 그래서 무조건 웹뷰로 구현해야하는 상황인 것 같은데 아무래도 카카오API 를 활용하면 유리한 공모전이기도 하고, 본래는 시간이 오래걸리더라도 가이드라인만 명확하면 천천히 배우고 따라해볼 의향이 있었는데 자료가 너무 희박하고(여차하면 제가 작성한 질문글과 블로그글이 검색 상단에 뜰정도), 여태껏 그나마 찾은 자료들도 아래와 같이 설명이 불분명해서 .. (제가 아직 경험이 부족해서 이해를 잘 못하는 것일수도 있어서 혹시나 해서 다른 분들 확인용으로 아래에 *웹뷰 구현관련 링크 첨부해두었는데 읽어보시고 괜찮으신 것 같으면 역할분담을 바꾸는 것도 좋은방법이지 않을까 싶습니다..! 근데 실제 웹뷰로 띄우는것에 성공을 한다고 하더라도 네이티브 구글 지도를 이용하는 것보다 성능도 떨어지고 웹서버도 따로 세팅을 해야하고, 연결 및 사용자 경험도 부자연 스러워질 것 같은데 이것이 개발할때 좋은 방법일지는 의문입니다...! )
> 
> 혹시 어플리케이션 웹뷰로 구현해보신 분 계신가요?! 어디서부터 어떻게 공부하고 어떤식으로 연결을 시작해야할지 잘 모르겠네요 .. 혹시 관련하여 참고할만한 자료가 있을까요?
> 
> 그래서 보통 일반적으로 React-Native 로 개발할때는 대부분 호환이 잘되는 구글맵을 이용하시는 것 같은데 어떻게 생각하시나요?
> 
> ***React-Native 에서 kakao map 웹뷰로 띄우기**
> 
> https://webruden.tistory.com/302
> 
> @JangAyeon @dazzlynnnn @SJ-Lee33

저는 웹뷰는 사용해본 적 없고, 네이티브 코드 (안드로이드 자바코드)를 react native에서 모듈화해 사용하는 것까지는 해봤습니다..!

**Comment by flowersayo** [comment]
# Android 애뮬레이터 location 설정

![image](https://user-images.githubusercontent.com/86418674/182365722-babd268d-30ca-44af-a668-c8044ba3198f.png)
