### ISSUE TITLE
Show modal using Recoil

### ISSUE THREAD

**Issue by SJ-Lee33** [EFUB-ZEJE/ZEJE-FrontEnd#12]
# ✨ Recoil을 사용해 모달 띄우기

---

# 1. State 생성

## 1) 설명
모달별로 유니크한 이름을 짓고, 같은 이름으로 `key` 값을 줍니다.
## 2) 위치
`src/modal/recoil/modalStates.js`

---

# 2. hook 생성
## 1) 설명
1번에서 생성한 state를 활용해, 모달 관리에 관한 함수를 어느 컴포넌트에서든 불러올 수 있도록 hook을 생성합니다.
## 2) 위치
`src/modal/recoil/useModals.js`

---

# 3. Modal 생성
## 1) 설명
모달을 생성합니다.
가장 상위 컴포넌트로는 생성해둔 `ModalSheet`를 활용하셔도 됩니다.

## 2) 폴더 위치
`src/modal/modals`

+) 모달 안에서 사용할 컴포넌트는 다른 폴더에 만들어 주시면 좋을 것 같습니다.

---

# 4. Modal 열기
## 1) 설명
모달을 열고 싶은 곳에서, 2번에서 생성한 훅을 불러옵니다.
그리고 `openModal`을 버튼 등의 `onPress`에 속성으로 주시면 됩니다.

## 2) 예시
```
const {openModal} = useOrangeGoldModal();

...

return(
  <Pressable onPress={openModal}>
     ...
  </Pressable>
)
```

---

# 5. Modal 닫기
## 1) 설명
모달을 닫고 싶은 곳에서, 2번에서 생성한 훅을 불러옵니다.

그리고
 `isModalOpen`을 `ModalSheet`의 `isModalOpen`에,
 `closeModal`을 `ModalSheet`의 `closeModal`에 속성으로 줍니다.

## 2) 예시
```
const {isModalOpen, closeModal} = useOrangeGoldModal();

...

return(
   <ModalSheet isModalOpen={isModalOpen} closeModal={closeModal}>
     ...
  </ModalSheet>
)
```

**Comment by flowersayo** [comment]
감사합니다! 혹시 React Native 자체에서 제공하는 Modal 컴포넌트가 있는데
모달을 꼭 Recoil 이용해서 띄우시는 이유가 있나요?!

https://reactnative.dev/docs/modal

**Comment by SJ-Lee33** [comment]
저걸 활용합니다!
다만 모달을 불러오는 횟수가 많을 것 같은데, 그때마다 useState를 사용하는 자원을 아껴보고자 recoil을 사용해 보았습니당
recoil 없이도 모달 사용이 가능하니 개발하면서 성능이나 사용성 비교해보면 좋을듯합니다

**Comment by flowersayo** [comment]
아하 그렇군요 저도 궁금해서 관련 정보 (https://dev.to/leoarada/recoil-hook-global-514) 찾아봤습니다 확실히 홈에는 모달사용할일이 많으니 성능개선에 도움을 받을 수 있을 것 같네요 소진님덕에 좋은 지식 배워갑니당,, 답변 감사합니다 !!:)

**Comment by flowersayo** [comment]
정리 감사하비다

> # ✨ Recoil을 사용해 모달 띄우기
> # 1. State 생성
> ## 1) 설명
> 모달별로 유니크한 이름을 짓고, 같은 이름으로 `key` 값을 줍니다.
> 
> ## 2) 위치
> `src/modal/recoil/modalStates.js`
> 
> # 2. hook 생성
> ## 1) 설명
> 1번에서 생성한 state를 활용해, 모달 관리에 관한 함수를 어느 컴포넌트에서든 불러올 수 있도록 hook을 생성합니다.
> 
> ## 2) 위치
> `src/modal/recoil/useModals.js`
> 
> # 3. Modal 생성
> ## 1) 설명
> 모달을 생성합니다. 가장 상위 컴포넌트로는 생성해둔 `ModalSheet`를 활용하셔도 됩니다.
> 
> ## 2) 폴더 위치
> `src/modal/modals`
> 
> +) 모달 안에서 사용할 컴포넌트는 다른 폴더에 만들어 주시면 좋을 것 같습니다.
> 
> # 4. Modal 열기
> ## 1) 설명
> 모달을 열고 싶은 곳에서, 2번에서 생성한 훅을 불러옵니다. 그리고 `openModal`을 버튼 등의 `onPress`에 속성으로 주시면 됩니다.
> 
> ## 2) 예시
> ```
> const {openModal} = useOrangeGoldModal();
> 
> ...
> 
> return(
>   <Pressable onPress={openModal}>
>      ...
>   </Pressable>
> )
> ```
> 
> # 5. Modal 닫기
> ## 1) 설명
> 모달을 닫고 싶은 곳에서, 2번에서 생성한 훅을 불러옵니다.
> 
> 그리고 `isModalOpen`을 `ModalSheet`의 `isModalOpen`에, `closeModal`을 `ModalSheet`의 `closeModal`에 속성으로 줍니다.
> 
> ## 2) 예시
> ```
> const {isModalOpen, closeModal} = useOrangeGoldModal();
> 
> ...
> 
> return(
>    <ModalSheet isModalOpen={isModalOpen} closeModal={closeModal}>
>      ...
>   </ModalSheet>
> )
> ```

정리감사합니다! 이 방법 참고해서 모달 띄워보도록 하겠습니다 :)
